language: haskell
ghc:
- 7.8
- 7.6
install:
  - cabal install --only-dependencies --enable-tests --constraint mtl==2.1.2
script:
  - cabal configure --enable-tests && cabal build && dist/build/tests/tests
